# Generated by Django 3.0.3 on 2021-02-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
