# Generated by Django 3.1.6 on 2021-03-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_comment_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
